package ppt;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

public class Final extends javax.swing.JFrame {

    int sB = 0, sJ = 0;

    public Final() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setSize(400, 250);

        sB = Juego.sB;
        sJ = Juego.sJ;
        

        if (sJ > sB) {
            jLabel_Titulo.setText("Felicidades ganaste.");
        } else if (sB > sJ) {
            jLabel_Titulo.setText("Lo siento perdiste.");
        } else if (sB == sJ) {
            jLabel_Titulo.setText("<html>Empate, quieres<br>jugar de nuevo?</html>");
        }

    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/tijera.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jButton_Reiniciar = new javax.swing.JButton();
        jButton_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 130));

        jButton_Reiniciar.setText("Juego nuevo");
        jButton_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ReiniciarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        jButton_Salir.setText("Salir");
        jButton_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ReiniciarActionPerformed
        dispose();
        new Juego().setVisible(true);
        sB = 0;
        sJ = 0;
    }//GEN-LAST:event_jButton_ReiniciarActionPerformed

    private void jButton_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalirActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por jugar.");
        dispose();
    }//GEN-LAST:event_jButton_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Reiniciar;
    private javax.swing.JButton jButton_Salir;
    private javax.swing.JLabel jLabel_Titulo;
    // End of variables declaration//GEN-END:variables
}
